Feature/71/enemy random movement
sesem4/Nelda pull request #106
Opened 2023-05-09 14:22 UTC by Muhammed-als

2023-05-10 17:06 UTC, MGertz approved these changes
LGTM

2023-05-10 20:22 UTC, The0mikkel reviewed
There is a few things with formatting. If everyone else is alright with that, then I am too.

2023-05-10 20:22 UTC, The0mikkel commented on RandomMovement/src/main/java/module-info.java
> +
Seems like there is a lot of empty lines just floating here?

2023-05-10 20:30 UTC, Muhammed-als commented on RandomMovement/src/main/java/module-info.java
> +
I have removed the empty lines 👍

2023-05-11 06:17 UTC, The0mikkel approved these changes

2023-05-11 08:27 UTC, JfriisJ approved these changes
looks good

2023-05-11 08:39 UTC, jakob753951 requested changes
close, but no cigar

2023-05-11 08:39 UTC, jakob753951 commented on Common/src/main/java/dk/sdu/sesem4/common/data/controllerParts/ControlType.java
> +    DUMBAI,
underscores mellem ord?

2023-05-11 09:07 UTC, jakob753951 approved these changes
LGTM

2023-05-11 09:11 UTC, MGertz approved these changes
JUST MERGE THIS SHIT

2023-05-11 09:11 UTC, merged

2023-05-11 09:12 UTC, The0mikkel approved these changes