Add collidedWithMap and add GameData to collided calls
sesem4/Nelda pull request #113
Opened 2023-05-11 13:09 UTC by jakob753951

2023-05-11 13:10 UTC, MGertz approved these changes
LGTM

2023-05-11 15:21 UTC, The0mikkel requested changes
Missing some JavaDoc

2023-05-11 15:49 UTC, jakob753951 commented on Common/src/main/java/dk/sdu/sesem4/common/data/entity/Entity.java
> +	public void collided(GameData gameData, Entity other) {
JavaDoc has been added :)

2023-05-11 15:49 UTC, jakob753951 commented on Common/src/main/java/dk/sdu/sesem4/common/data/entity/Entity.java
> +	public void collidedWithMap(GameData gameData) {
JavaDoc has been added :)

2023-05-11 17:59 UTC, Muhammed-als approved these changes
LGTM

2023-05-11 20:32 UTC, The0mikkel approved these changes

2023-05-11 20:32 UTC, The0mikkel commented
Please wait for #119 (Sprint 3) to be merged, before merging this one

2023-05-12 05:40 UTC, JfriisJ approved these changes
looks good

2023-05-15 22:20 UTC, MGertz approved these changes

2023-05-18 07:16 UTC, The0mikkel approved these changes

2023-05-18 07:17 UTC, merged