Feature / 73 / Simple AI
sesem4/Nelda pull request #133
Opened 2023-05-21 19:44 UTC by The0mikkel

This closes #73

2023-05-21 19:52 UTC, MGertz approved these changes
LGTM

2023-05-22 06:22 UTC, JfriisJ requested changes
we should only pull request on a single component there might be breaking changes in this.

2023-05-22 06:22 UTC, JfriisJ commented on Common/src/main/java/dk/sdu/sesem4/common/util/Direction.java
> +	UP, DOWN, LEFT, RIGHT,NONE
Why use NONE instead of null ?

2023-05-22 06:22 UTC, JfriisJ commented on SmartAI/src/main/java/dk/sdu/sesem4/smartAIMovement/SmartAIMovement.java
This should be another pull request

2023-05-22 06:22 UTC, JfriisJ commented on SmartAI/src/main/java/dk/sdu/sesem4/smartAIMovement/SmartAIMovementController.java
This should be another pull request

2023-05-22 06:22 UTC, JfriisJ commented on SmartAI/src/main/java/module-info.java
This should be another pull request

2023-05-22 06:22 UTC, JfriisJ commented on SmoothRandomMovement/pom.xml
This should be another pull request

2023-05-22 06:22 UTC, JfriisJ commented on SmoothRandomMovement/src/main/java/dk/sdu/sesem4/SmoothRandomMovement/SmoothRandomMovement.java
This should be another pull request

2023-05-22 06:22 UTC, JfriisJ commented on SmoothRandomMovement/src/main/java/dk/sdu/sesem4/SmoothRandomMovement/SmoothRandomMovementController.java
This should be another pull request

2023-05-22 06:22 UTC, JfriisJ commented on SmoothRandomMovement/src/main/java/module-info.java
This should be another pull request

2023-05-22 11:18 UTC, Muhammed-als approved these changes
LGTM

2023-05-22 15:13 UTC, The0mikkel commented on Common/src/main/java/dk/sdu/sesem4/common/util/Direction.java
> +	UP, DOWN, LEFT, RIGHT,NONE
Removed None, I agree, that `NONE` should be represented with null.

2023-05-23 07:25 UTC, JfriisJ approved these changes
Keep up the work

2023-05-23 07:27 UTC, merged