Bugfix/123/make boundarybox smaller for all entities
sesem4/Nelda pull request #134
Opened 2023-05-22 13:01 UTC by JfriisJ

2023-05-22 13:03 UTC, MGertz approved these changes
LGTM

2023-05-22 13:03 UTC, The0mikkel requested changes

2023-05-22 13:03 UTC, The0mikkel commented on Map/src/main/java/dk/sdu/sesem4/map/MapUtil.java
> +		float epsilon = 2.0f;
This name clashes with `yAxisEpsilon`

2023-05-22 13:08 UTC, The0mikkel requested changes

2023-05-22 13:08 UTC, The0mikkel commented on Map/src/main/java/dk/sdu/sesem4/map/MapUtil.java
>  		return bottomLeftPassible && bottomRightPassible && topLeftPassible && topRightPassible;
This must be documented in the code. The code in itself is not self describing, and we should not rely on self describing code.

2023-05-23 06:34 UTC, Muhammed-als approved these changes
LGTM

2023-05-23 06:34 UTC, Muhammed-als commented on Map/src/test/java/dk/sdu/sesem4/map/MapUtilTest.java
>  		for (java.util.Map.Entry<Vector2, Boolean> entrySet : positions.entrySet()) {
Import the library instead of using it in the for loop

2023-05-23 07:10 UTC, The0mikkel requested changes

2023-05-23 07:10 UTC, The0mikkel commented on Map/src/test/java/dk/sdu/sesem4/map/MapUtilTest.java
>  		for (java.util.Map.Entry<Vector2, Boolean> entrySet : positions.entrySet()) {
I agree with this. It is not good practice to use full path I believe

2023-05-23 07:19 UTC, MGertz commented on Map/src/test/java/dk/sdu/sesem4/map/MapUtilTest.java
>  		for (java.util.Map.Entry<Vector2, Boolean> entrySet : positions.entrySet()) {
This has been approved long time ago. its not part of the changes in this issue. 

Lets move on, or at least create a separate bugfix for this. as its not related to the changes here.

2023-05-23 07:30 UTC, JfriisJ commented on Map/src/test/java/dk/sdu/sesem4/map/MapUtilTest.java
>  		for (java.util.Map.Entry<Vector2, Boolean> entrySet : positions.entrySet()) {
agree with MGertz, create a new issue based on that specific change.

2023-05-23 07:32 UTC, merged