Feature - 30 - Create SPI's
sesem4/Nelda pull request #36
Opened 2023-03-29 10:42 UTC by The0mikkel

This update adds all designed SPI's to the system.  
Due to the nature of the SPI's and current development status, classes that are used by the SPI's, has been created, but left empty.

This resolves #30

2023-03-29 12:19 UTC, jakob753951 requested changes

2023-03-29 12:19 UTC, jakob753951 commented on docs/SPI/ControlSPI.md
> +float[] move(GameData gameData, Entity entity)
should return a `Vector2` (a delta position) instead of a `float[]`

2023-03-29 12:19 UTC, jakob753951 commented on docs/SPI/RegionSPI.md
> +Region loadRegion(GameData gameData, Map map)
we are removing region

2023-03-29 12:55 UTC, jakob753951 requested changes

2023-03-29 12:55 UTC, jakob753951 commented on Common/src/main/java/dk/sdu/sesem4/common/SPI/EventServiceSPI.java
> +     * Spawn enemy into the map
Is this line correct?

2023-03-29 14:40 UTC, The0mikkel commented on Common/src/main/java/dk/sdu/sesem4/common/SPI/PickupSPI.java
> +     * @return The item that is to be picked up
This will be discussed at a further date

2023-03-30 11:01 UTC, The0mikkel commented on Common/src/main/java/dk/sdu/sesem4/common/SPI/PickupSPI.java
> +     * @return The item that is to be picked up
We will change this to void and generally make pickUp a way to tell the item, that it has been picked up, and therefore should probably not be shown in the world

2023-03-30 11:16 UTC, JfriisJ approved these changes

2023-03-30 11:17 UTC, JfriisJ approved these changes
Looks good

2023-03-30 11:19 UTC, Muhammed-als approved these changes

2023-03-30 11:40 UTC, jakob753951 requested changes

2023-03-30 11:59 UTC, The0mikkel commented on docs/SPI/CombatSPI.md
> +`Entity weapon` - The entity that spawns the weapon
The entity itself will from the entity (combatee) find the position it shall spawn, so that the component itself can change it.

2023-03-30 12:05 UTC, AnneLaerke approved these changes
✨

2023-03-30 12:09 UTC, jakob753951 approved these changes
LGTM

2023-03-30 12:09 UTC, merged