Feature - 41 - Event system
sesem4/Nelda pull request #44
Opened 2023-04-10 19:49 UTC by The0mikkel

This update contains an Event system, that allows for events to be emitted to a list of subscribers.

The update builds upon the [Observer-](https://refactoring.guru/design-patterns/observer) and [publish-subscribe- pattern](https://www.aiplusinfo.com/blog/observer-vs-pub-sub-pattern-what-is-the-difference/).  
With this, it is possible to subscribe to any event type, as well as notify any event type.

This update will close #41 

Class diagram:
![image](https://user-images.githubusercontent.com/28625667/230984726-8ec1a110-7908-4bc6-ac6c-29725e86e563.png)

Sequence diagram:
![image](https://user-images.githubusercontent.com/28625667/230984791-74b568a0-3e81-46c6-8756-9e82baafb8fa.png)

*These diagrams is located in the `docs` folder, under `diagrams -> Event`*

2023-04-10 20:56 UTC, jakob753951 requested changes
:)

2023-04-10 20:56 UTC, jakob753951 commented on Common/src/main/java/dk/sdu/sesem4/common/event/EventManager.java
> +        // Add the new listeener to the set
listener*

2023-04-10 20:56 UTC, jakob753951 commented on Common/src/main/java/dk/sdu/sesem4/common/event/EventManager.java
> +     * @param type EventType that is to be unsubscribed from. It may be a subclass.
Same as line 38

2023-04-10 20:56 UTC, jakob753951 commented on Common/src/main/java/dk/sdu/sesem4/common/event/EventManager.java
> +     * @param type EventType of the notification, and to which the notification is sent.
what does this mean?

2023-04-10 20:56 UTC, jakob753951 commented on Common/src/main/java/dk/sdu/sesem4/common/event/EventManager.java
> +        // If the type does not exist in the listernes map, no EventListener is present to be notified
*listeners

2023-04-10 20:56 UTC, jakob753951 commented on Common/src/main/java/dk/sdu/sesem4/common/event/EventManager.java
> +        // If the type does not exist in the listernes map, the listener can not be unsubscribed, because it was never subscribed.
listeners*

2023-04-10 20:56 UTC, jakob753951 commented on Common/src/main/java/dk/sdu/sesem4/common/event/EventManager.java
> +        // If the type does not exist in the listernes map, add a new set
listeners*

2023-04-10 20:56 UTC, jakob753951 commented on docs/diagrams/Event/sequenceDiagram.puml
> +Note right of Listener2: Listener2 unsubscribes to event type 1
Should we maybe have this in a separate block to show, that it can happen in separate process loops?
Maybe for brevity, just have a line saying "rest of the processing" and then "beginning of processing until this point"?

2023-04-11 07:45 UTC, jakob753951 approved these changes
LGTM

2023-04-11 07:46 UTC, Muhammed-als approved these changes

2023-04-11 07:46 UTC, MGertz approved these changes
c",)

2023-04-11 07:47 UTC, merged