Merge Prototype
sesem4/Nelda pull request #56
Opened 2023-04-25 06:57 UTC by jakob753951

Merge the prototype so the other teams can get started sooner

2023-04-26 10:22 UTC, MGertz approved these changes

2023-04-26 11:10 UTC, JfriisJ approved these changes
Remember the javadoc but looks fine with the changes

2023-04-26 11:10 UTC, JfriisJ commented on Collision/src/main/java/dk/sdu/sesem4/collision/Collision.java
missing javadoc.

2023-04-26 11:10 UTC, JfriisJ commented on Collision/src/main/java/dk/sdu/sesem4/collision/CollisionSystem.java
missing javadoc.

2023-04-26 11:10 UTC, JfriisJ commented on Common/src/main/java/dk/sdu/sesem4/common/data/EntityParts/PositionPart.java
missing javadoc.

2023-04-26 11:10 UTC, JfriisJ commented on Common/src/main/java/dk/sdu/sesem4/common/data/math/Vector2.java
> +     * Creates a new Vector with magnitude 1 and the given direction
missing param in javadoc

2023-04-26 11:10 UTC, JfriisJ commented on Common/src/test/java/dk/sdu/sesem4/common/data/EntityParts/PositionPartTest.java
missing javadoc.

2023-04-26 11:10 UTC, JfriisJ commented on Common/src/test/java/dk/sdu/sesem4/common/data/math/RectangleTest.java
missing descriptions.

2023-04-26 11:10 UTC, JfriisJ commented on Map/src/main/java/dk/sdu/sesem4/map/MapProcessingService.java
> +
description missing.

2023-04-26 16:09 UTC, The0mikkel requested changes
Some minor changes. Mostly documentation and testing.

I have heard somethgin about everything not being tested?

In the pom.xml files, JUnit 4 is used, but `extends TestCase` is a JUnit 3 way of declaring test files.

2023-04-26 16:09 UTC, The0mikkel commented on Common/src/test/java/dk/sdu/sesem4/common/data/math/RectangleTest.java
> +public class RectangleTest extends TestCase {
TestCase is JUnit 3

2023-04-27 08:28 UTC, jakob753951 commented on Common/src/main/java/dk/sdu/sesem4/common/data/EntityParts/MovingPart.java
> -     */
It is self-describing

2023-04-27 12:11 UTC, jakob753951 commented on Collision/src/main/java/dk/sdu/sesem4/collision/CollisionSystem.java
> +public class CollisionSystem implements PostProcessingServiceSPI {
Has now been added

2023-04-27 12:11 UTC, jakob753951 commented on Collision/src/main/java/dk/sdu/sesem4/collision/Collision.java
>  public class Collision {
Has been added

2023-04-27 12:25 UTC, jakob753951 commented on Map/src/main/java/dk/sdu/sesem4/map/MapProcessingService.java
> +
Has been added

2023-04-27 12:31 UTC, Muhammed-als approved these changes

2023-04-27 12:32 UTC, The0mikkel approved these changes

2023-04-27 12:35 UTC, merged

2023-04-27 12:35 UTC, JfriisJ approved these changes