Feature/14/restrict entity movement to map
sesem4/Nelda pull request #67
Opened 2023-04-27 18:06 UTC by JfriisJ

2023-04-27 18:08 UTC, jakob753951 commented on Map/src/main/resources/overworld.tiled-session
We should add this file to the .gitignore

2023-04-27 18:10 UTC, jakob753951 commented
Looks Good Enough To Me

2023-04-27 19:02 UTC, JfriisJ commented on Map/src/main/resources/overworld.tiled-session
it has been deleted and added to git ignore

2023-04-27 19:16 UTC, MGertz requested changes

2023-04-27 19:16 UTC, MGertz commented on Map/src/main/java/dk/sdu/sesem4/map/MapPlugin.java
> +public class MapPlugin implements PluginServiceSPI, ProcessingServiceSPI, PostProcessingServiceSPI {
Why are these implemented here, when they are also implemented in MapProcessingService.java?

In this file, they are just calling the postProcess() and process() from MapProcessingService.java.

Which makes those two processes run twice.

2023-04-27 19:16 UTC, MGertz commented on Map/src/main/resources/overworld.tiled-session
agree

2023-04-27 19:16 UTC, MGertz commented on Player/src/main/java/dk/sdu/sesem4/player/Player.java
Only Accepting, file because it will be overwritten with Feature/49/Create-Player  is merged into develop

2023-04-27 19:16 UTC, MGertz commented on Player/src/main/java/dk/sdu/sesem4/player/PlayerPlugin.java
Only Accepting, file because it will be overwritten with Feature/49/Create-Player  is merged into develop

2023-04-27 19:16 UTC, MGertz commented on Player/src/main/java/dk/sdu/sesem4/player/PlayerProcessingService.java
Only Accepting, file because it will be overwritten with Feature/49/Create-Player  is merged into develop

2023-04-27 19:16 UTC, MGertz commented on Player/src/main/java/module-info.java
Only Accepting, file because it will be overwritten with Feature/49/Create-Player  is merged into develop

2023-04-27 19:35 UTC, JfriisJ commented on Map/src/main/java/dk/sdu/sesem4/map/MapPlugin.java
> +public class MapPlugin implements PluginServiceSPI, ProcessingServiceSPI, PostProcessingServiceSPI {
they have been removed

2023-04-27 19:36 UTC, MGertz approved these changes
LGTM

2023-04-27 20:23 UTC, jakob753951 requested changes
Almost perfect :)

2023-04-27 20:27 UTC, The0mikkel requested changes
Only minor formatting issue - Otherwise (without testing it) looks good

2023-04-27 20:27 UTC, The0mikkel commented on Map/src/main/java/dk/sdu/sesem4/map/MapPlugin.java
> +public class MapPlugin implements PluginServiceSPI{
This seems like wrong formatting?

2023-04-27 20:31 UTC, MGertz commented on .gitignore
> +overworld.tiled-session
resolved

2023-04-27 20:32 UTC, MGertz commented on Map/src/main/java/dk/sdu/sesem4/map/MapPlugin.java
> +public class MapPlugin implements PluginServiceSPI{
fixed

2023-04-28 06:12 UTC, Muhammed-als commented on Map/src/main/java/dk/sdu/sesem4/map/MapProcessingService.java
>  		String[] columns = new String[]{"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"};
It is possible to convert this array to char?
You can simplify this array by writing:
char[] columns = new char[26]
for(int i = 0; i<columns.length; i++){
columns[i] = (char) ('A' + i);
}
In this way you can create the array columns without writing down all the letters

2023-04-28 07:05 UTC, jakob753951 commented on Map/src/main/java/dk/sdu/sesem4/map/MapProcessingService.java
>  		String[] columns = new String[]{"A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"};
This has now been implemented.
Great solution!

2023-04-28 07:10 UTC, Muhammed-als approved these changes
LGTM!

2023-04-28 10:42 UTC, merged