Feature/49/create player
sesem4/Nelda pull request #90
Opened 2023-05-04 12:55 UTC by JfriisJ

2023-05-04 15:43 UTC, jakob753951 requested changes

2023-05-04 18:17 UTC, MGertz commented on Player/src/main/java/dk/sdu/sesem4/player/PlayerProcessingService.java
> +	private void mapTransition(GameData gameData, PositionPart positionPart) {
Done

2023-05-04 18:21 UTC, MGertz commented on Player/src/main/java/dk/sdu/sesem4/player/Player.java
Correct, but the information is stored in this class, so that they are easy to change, in case anyone wants more life, speed etc. It could ofcause be hardcoded directly into the Parts where they are set in the PlayerPlugin.class file.

They have been changed to final and the set methods have been removed.

2023-05-06 13:50 UTC, The0mikkel requested changes

2023-05-06 13:50 UTC, The0mikkel commented on Player/src/main/java/dk/sdu/sesem4/player/Player.java
> +	private Direction direction = Direction.UP;
Why is direction needed here?

2023-05-06 13:50 UTC, The0mikkel commented on Player/src/main/java/dk/sdu/sesem4/player/PlayerPlugin.java
> +			}
This should be moved to the control system

2023-05-06 13:50 UTC, The0mikkel commented on Player/src/main/java/dk/sdu/sesem4/player/PlayerProcessingService.java
> +			positionPart.process(gameData, player);
This could be a very nice addition, but this is not something that is implemented currently in the entity.

I would assume such a method could be of use, or otherwise an intermediate method could be implemented on the entity, to process all of its parts.

2023-05-06 13:50 UTC, The0mikkel commented on Player/src/main/java/dk/sdu/sesem4/player/PlayerProcessingService.java
> +		float rightEdge = 16 * 16; //TODO create a method in gameData that returns the map size
This should be loaded from GameData

2023-05-06 13:50 UTC, The0mikkel commented on Player/src/main/java/module-info.java
> +	requires ShadedLibGDX;
This should not be needed

2023-05-06 13:50 UTC, The0mikkel commented on Player/pom.xml
> +		</dependency>
This should not be needed

2023-05-06 20:35 UTC, jakob753951 commented on Player/src/main/java/dk/sdu/sesem4/player/Player.java
It doesn't need to be hardcoded at all. All of this information is stored in the parts already.
All this does is store the data twice, and it might not even be the same data, even though it should be.

2023-05-06 20:36 UTC, jakob753951 requested changes
Please use EntityParts instead of storing information directly on Player unless necessary.

2023-05-06 20:37 UTC, The0mikkel commented on Player/src/main/java/dk/sdu/sesem4/player/Player.java
I think what was thought of, when doing this, is to have a place to store the initial data points for the enemy.  
But really, this is where the plugin comes in. The plugin is what creates the entity, so it could be, that these "start" values should be set as finals on the plugin, rather than on the entity?

2023-05-06 20:38 UTC, The0mikkel commented
> Please use EntityParts instead of storing information directly on Player unless necessary.

I think that this misses the point. The current system does not use the data in the enemy as the values instead of parts, it just represents the start values. I do suggest, however, that these values are moved somewhere, where it better represents that it is the start data?

2023-05-07 20:28 UTC, MGertz commented on Player/src/main/java/dk/sdu/sesem4/player/Player.java
Moved all those variables to PlayerPlugin

2023-05-07 20:28 UTC, MGertz commented on Player/src/main/java/dk/sdu/sesem4/player/PlayerPlugin.java
> +			}
updated to use KeyboardController

2023-05-07 20:29 UTC, MGertz commented on Player/src/main/java/dk/sdu/sesem4/player/Player.java
> +	private Direction direction = Direction.UP;
Its used when PositionPart is set.

2023-05-07 20:32 UTC, MGertz commented on Player/src/main/java/module-info.java
> +	requires ShadedLibGDX;
True Removed

2023-05-07 20:32 UTC, MGertz commented on Player/pom.xml
> +		</dependency>
true Removed

2023-05-07 20:34 UTC, MGertz commented on Player/src/main/java/dk/sdu/sesem4/player/PlayerProcessingService.java
> +			positionPart.process(gameData, player);
True. But is it really that nessesary for this project?

2023-05-07 20:45 UTC, MGertz commented on Player/src/main/java/dk/sdu/sesem4/player/PlayerProcessingService.java
> +		float rightEdge = 16 * 16; //TODO create a method in gameData that returns the map size
True, has been fixed now. but those methods didnt exists when the code was written

2023-05-07 21:06 UTC, jakob753951 approved these changes
Looks great 😄

2023-05-08 14:11 UTC, The0mikkel approved these changes

2023-05-08 18:14 UTC, Muhammed-als commented on Player/src/main/java/dk/sdu/sesem4/player/PlayerProcessingService.java
> +			positionPart.process(gameData, player);
public <E extends EntityPart> E getAllEntityParts(){
         	return (E) this.entityParts;
     }
I pretty sure that this is the method we need to get all the entity parts

2023-05-08 18:15 UTC, merged